#!/bin/sh
for n in $(kubectl get nodes | grep internal | awk '{print $1":"$2":"$4":"$5}'); do
	node=$(echo $n | awk -F: '{print $1}')
	uptime=$(echo $n | awk -F: '{print $3}')
	status=$(echo $n | awk -F: '{print $2}')
	version=$(echo $n | awk -F: '{print $4}')
	data=$(kubectl describe node $node|egrep "node.kubernetes.io/instance-type|InternalIP|topology.kubernetes.io/zone|capacity.*ype" | sed 's|:|=|g' | awk -F= '{print $2}');
	echo $node $status $uptime $data $version; 
done | column -t -N "NAME,STATUS,AGE,CAPACITY-TYPE,INSTANCE-TYPE,ZONE,INETRNAL-IP,VERSION"
